services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: deokhugam1234
      POSTGRES_USER: deokhugam_user
      POSTGRES_DB: deokhugam
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
#      - ./schema:/docker-entrypoint-initdb.d