spring:
  application:
    name: deokhugam
  profiles:
    active: dev   # dev, prod 선택 가능

# Naver API 설정 추가, .env 파일에서 주입받음, 환경변수 없을 시 테스트용 더미 사용
naver:
  api:
    client-id: ${NAVER_CLIENT_ID:default-test-id}
    client-secret: ${NAVER_CLIENT_SECRET:default-test-secret}

# AWS S3 설정, 환경변수에서 주입받음
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_S3_REGION:ap-northeast-2}
    bucket: ${S3_BUCKET_NAME:deokhugam-thumbnails}
    base-url: https://${S3_BUCKET_NAME:deokhugam-thumbnails}.s3.ap-northeast-2.amazonaws.com